spring:
  application:
    name: demoMySQL
  datasource:
    url: jdbc:mysql://localhost:3306/demodb
    username: root
    password: 12345
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true
  logging:
    level:
      org:
        springframework:
          security: DEBUG
